package com.supreme.spa.backend.vue.models;

public enum UserStatus {
    SUCCESSFULLY_REGISTERED,
    SUCCESSFULLY_AUTHED,
    SUCCESSFULLY_LOGGED_OUT,
    SUCCESSFULLY_CHANGED,
    SUCCESSFULLY_CREATED,
    ACCESS_ERROR,
    WRONG_CREDENTIALS,
    NOT_UNIQUE_USERNAME_OR_EMAIL,
    NOT_UNIQUE_PHONE,
    ALREADY_AUTHENTICATED,
    UNEXPECTED_ERROR,
    NOT_FOUND,
    MAGIC
}
